create table if not exists newsletter (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table newsletter enable row level security;

create policy "Enable insert for everyone"
on "public"."newsletter"
as PERMISSIVE
for INSERT
to public
with check (true);

create policy "Enable read access for authenticated users only"
on "public"."newsletter"
as PERMISSIVE
for SELECT
to authenticated
using (true);
